### ISSUE TITLE
Callbacks and security

### ISSUE THREAD

**Issue by strogonoff** [markwylde/workerbox#23]
Hi and thanks for an interesting project!

Curious about the `setCallback` example in the README; wouldn’t calling `fn()` in host context be insecure? If the plugin can pass an arbitrary function, when it’s executed wouldn’t it be able to gain access to host context?

**Comment by strogonoff** [comment]
I mean this example:

```js
let callback;
const scope = {
  name: 'Mark',
  getMessage: () => 'Have a great day!',
  setCallback: fn => {
    // You can store arguments, objects, arrays and returned values
    // outside of the scope of your main app, and then call them
    // from anywhere, so long as the worker is not destroyed.
    callback = fn;
  }
};

setInterval(() => {
  if (callback) {
    // This will communicate with the workerbox transparently.
    callback();
  }
});
```

Notably, the example doesn’t actually use `setCallback()` within the evaluated plugin side, so there is no further explanation…

**Comment by markwylde** [comment]
Hey @strogonoff. Sorry the docs aren't that clear. I should add some `setCallback` usage, or change the demo a bit. Not sure of a better/real world scenario though.

But to explain, everything between the host and workerbox is sent in JSON via messages posted back and forth between each other.

So what happens when when you call `setCallback`, is a [uniqueId](https://github.com/markwylde/workerbox/blob/master/lib/createCallbackStore.js#L7) is generated, and stored in memory on both the host and client. When you later call the "callback" function, it actually just sends a message to the workerbox, saying "run callback id XXX".

Maybe a clearer way of explaining it would be to say, if you run `setCallback` but then destroy the workerbox, the code will not work.

**Comment by strogonoff** [comment]
Thanks for the explanation!
